Added namespaceOverride value
enix/x509-certificate-exporter pull request #185
Opened 2023-09-08 10:38 UTC by Flyffies

Hi,

I ran into a niche Situation where I need to deploy the chart as a a depdency to my primary one but would like to override the target namespace only for the x509 chart.

I compared how other charts do this and it seemed easy to add.
I thought others might also enjoy this small addition.

2023-09-08 11:05 UTC, npdgm requested changes
Hi @Flyffies, thanks for taking the time to implement this. That's a great addition to the chart :+1: 

I see the `namespace` property was set on resources that are not namespaced, so it's probably not going to be accepted by Kubernetes at all. Also there are still two occurences of `{{ .Release.Namespace }}` in the ClusterRoleBindings.
Could you please make those corrections? 
Thanks a lot

2023-09-08 11:05 UTC, npdgm commented on deploy/charts/x509-certificate-exporter/templates/clusterrolebinding.yaml
Could you please add the new namespace template to the two ServiceAccounts mapped in this file? There are occurences of `.Release.Namespace`. Thanks!

2023-09-08 11:28 UTC, Flyffies commented
Ahh yes, seems I blindly just put a namespace to every resource... Fixed with the new commit.

2023-09-08 11:31 UTC, npdgm commented
> Ahh yes, seems I blindly just put a namespace to every resource... Fixed with the new commit.

Thanks a lot, and no worries I almost missed it too :)
If you don't mind we'll release this after the weekend as there is a change I want to make to the CI before.
Cheers

2023-09-08 11:40 UTC, merged

2023-09-08 12:04 UTC, Flyffies commented
Thanks, after the weekend will be wonderful.
Have a nice one!

2023-09-11 11:53 UTC, monkeynator commented
:tada: This PR is included in version 3.10.0 :tada:

The release is available on [GitHub release](https://github.com/enix/x509-certificate-exporter/releases/tag/untagged-e4c40c286657323c98ab)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-11 12:09 UTC, monkeynator commented
:tada: This PR is included in version 3.10.0 :tada:

The release is available on [GitHub release](https://github.com/enix/x509-certificate-exporter/releases/tag/untagged-11a108ffe629ab50e6ff)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: