chore: add probes on all containers
enix/x509-certificate-exporter pull request #234
Opened 2024-01-18 11:26 UTC by zwindler

Hello,

I'm deploying this exporter on my cluster and we have a Kyverno policy that requires all pods to have liveness/readiness probes

Since those are exporters containers, I felt it was not a bad thing to make sure that the exporter is indeed listening on the exposed port

It's best practice to not have liveness === readiness but in this case I think this is acceptable, unless you want to take the time to create proper HTTP endpoints in the code to add a /live and a /ready (I can do it but I'm not sure this is worth it)

2024-03-22 16:49 UTC, paullaffitte requested changes
Hi! Thanks for your contribution!

The `/metrics` endpoint generate metrics on the fly, so relying on it for probes isn't very cost-efficient. Could you add and use a `/healthz` endpoint instead? The liveness and readiness probes can both rely on it. You don't have to implement any logic, in the futur we could think about implementing some real checks, but for now simply responding would be enough.

2024-03-24 07:08 UTC, zwindler commented
Sure, that makes much more sense

I'll work on this soon and will update the branch

2024-03-25 14:56 UTC, zwindler commented
@paullaffitte I added a super basic handler to the ServeMux (/healthz as suggested)

2025-02-19 17:38 UTC, plaffitt approved these changes

2025-02-19 17:38 UTC, merged

2025-06-19 15:31 UTC, monkeynator commented
:tada: This PR is included in version 3.19.0-beta.1 :tada:

The release is available on [GitHub release](https://github.com/enix/x509-certificate-exporter/releases/tag/untagged-8028f428e464e80c0f0f)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-06-19 15:41 UTC, monkeynator commented
:tada: This PR is included in version 3.19.0 :tada:

The release is available on [GitHub release](https://github.com/enix/x509-certificate-exporter/releases/tag/untagged-30affbcc737e66c106da)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: